server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    key: ENC(jDN6MelNebup48sgKD8CEyXxG/wRebMMp05fW0mbi1wZ+aOBn6QcDyyGFI3cHUPQsFPGZ0q4hjBYz7f9visNC6QG7CwD5fJWBYGdKu7UHRF3Knm2JRmjZKHcnyQG9K/P)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
